### ISSUE TITLE
Remove commented code from scripts.

### ISSUE THREAD

**Issue by srakhe** [srakhe/olympics#15]
**Describe the bug**
Remove some minor commented code in https://github.com/srakhe/olympics/blob/main/scripts/analysis/sentiment/sentiment_analysis_tokyo.py.

**Comment by leonardsangoroh** [comment]
@srakhe Do you mind if I remove the commented code?

If not, feel free to assign the issue to me

**Comment by srakhe** [comment]
@leonardsangoroh Unfortunately this is currently a project under the development of a closed team, but we will open new issues that need outside help when the development of this project continues in the future. Thanks for offering to contribute!

**Comment by srakhe** [comment]
This file has been modified and moved in #23 , closing this issue.
